### ISSUE TITLE
[ USER STORY 1 ] - As a user I want to be able to search an "event, topic, article title, author, publisher, location" and get articles related to it, on the sift website.

### ISSUE THREAD

**Issue by jferreira** [jferreira/sift#3]

**Comment by rogermutt** [comment]
Route:
GET
HTML Response 
events#index/query

Events Index will need to return:
- List of events and the parent topic of each one 
- Order criteria TBC 

Links:
Profile Section > get profile#view
Event Card > get events#show

HTLM Components:
Nav
Search Box (includes value typed in)
Event-Card

**Comment by jferreira** [comment]
https://marvelapp.com/48iech3/screen/50330727
[Uploading... Screen Shot 2018-11-15 at 14.41.46.png ]
