### ISSUE TITLE
[FEATURE ] Next / Previous article from article#show

### ISSUE THREAD

**Issue by rogermutt** [jferreira/sift#41]

**Comment by jferreira** [comment]
http://tesoriere.com/2012/01/12/rails--next-and-previous-links-for-a-post--article--or-any-model/

**Comment by jferreira** [comment]
![Screen Shot 2018-11-16 at 12.36.51.png](https://images.zenhubusercontent.com/59db4129b0222d5de47ad5ee/892eb9e7-0cf3-4997-bbb4-702c681e06e5)

**Comment by jferreira** [comment]
<%# if article.previous.presence? %>
        <%#  article_previous = article.previous %>
        <%#= link_to "Previous Article", article_path(article_previous), class: "btn btn-primary" %>
      <%# end %>

**Comment by jferreira** [comment]
![Screen Shot 2018-11-16 at 14.36.02.png](https://images.zenhubusercontent.com/59db4129b0222d5de47ad5ee/aa86764f-89b1-4442-af16-a523a728496c)
