### ISSUE TITLE
[ USER STORY 7 ] As a user I want to be able to rate the quality of an article (Up to +5, or Down to -5)

### ISSUE THREAD

**Issue by jferreira** [jferreira/sift#9]
![Screen Shot 2018-11-17 at 11.52.55.png](https://images.zenhubusercontent.com/59db4129b0222d5de47ad5ee/3ce35cca-7936-4dde-8859-1d589c4ed2ef)

**Comment by rogermutt** [comment]
The action will happen in articles#show/:id

Route:
POST
HTML Response 
'scores',  to: 'user_scores#create

View:
- Display form for  rate_up / rate_down with the article id contained in it
- Form to contain field with value 5

Controller:
- Create new score with user id, article id and user score 
- redirect to articles#show/:id
(We require articles#show/:id to retrieve all scores each time)

HTLM Components:
Rating Card form (same for both)
